default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_travel_logger_development

test:
  <<: *default
  database: rails_travel_logger_test

production:
  <<: *default
  database: rails_travel_logger_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>